<?php
// $Id$

/**
 * @file
 * Simple filter module for Drupal
 *
 * Filters content for URLs and adds a class reflecting their target.
 *
 * @author
 * Stefan Auditor <stefan.auditor@erdfisch.de>
 * for erdfisch :: internetlösungen http://erdfisch.de
 */

/**
 * Implementation of hook_help().
 */
function urlclass_help($section) {
  switch ($section) {
    case 'admin/help#urlclass':
      $output = '<p>'. t('The URLClass module automatically adds a CSS class to &lt;a&gt;-elements reflecting their target.') .'</p>';
      $output .= '<p>'. t('Use Input Formats to enable the URL filter') .'</p>';
      $output .= t('<ol><li>Select an existing Input Format or add a new one</li><li>Configure the Input Format</li><li>Enable URL class filter and Save configuration</li><li>Rearrange the weight of the URL filter depending on what filters exist in the format</li></ol>');
      $output .= '<p>'. t('You can enable the urlfilter for an input format from <a href="%admin-filters">Administer &gt;&gt; Site Configuration &gt;&gt; Input Filter</a>.', array('%admin-filters' => url('admin/settings/filters'))) .'</p>';
      return $output;
  }
}

/**
 * Implementation of hook_menu().
 */
function urlclass_menu($may_cache) {
  drupal_add_css(drupal_get_path('module', 'urlclass') .'/urlclass.css', 'module');
}

/**
 * Implementation of hook_filter().
 */
function urlclass_filter($op, $delta = 0, $format = -1, $text = '') {
  switch ($op) {
    case 'list':
      return array(0 => t('URL Class filter'));
    
    case 'description':
      return t('Adds a CSS class to a URL.');
    
    case 'process':
      $text = preg_replace_callback('/<a.+?href=\"(http:\/\/.+?)\"[^>]*>.+?<\/a>/i', 'urlclass_replace', $text);
      return $text;
    
    default:
      return $text;
  }
}

/**
 * Callback function for the filter
 */
function urlclass_replace($match) {
  $url = parse_url($match[1]);
  $domain = explode('.', $url['host']);
  $domain = $domain[(count($domain)-2)];
  
  if (stristr($match[0], 'class')) $match[0] = str_replace('class="', 'class="uc-'. check_plain($domain) .' ', $match[0]);
  else $match[0] = str_replace('">', '" class="uc-'. check_plain($domain) .'">', $match[0]);
  
  return $match[0];
}
